version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      POSTGRESQL_HOST: database
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: test
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend
    links:
      - database
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5433:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
