apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::036310137459:user/ecs-deploy
      username: ecs-deploy
      groups:
        - system:masters
